name: benchmark_framework_x
description: Experimental benchmarking framework in dart
version: 0.1.0
homepage: https://github.com/winksaville/dart_benchmark_framework_x.git

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  benchmark_harness: ^1.0.0
  stats: ^1.0.0

dev_dependencies:
  intl: ^0.16.0
  mockito: ^4.1.1
  pedantic: ^1.8.0
  test: ^1.6.0


