name: benchmark_example
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/winksaville/benchmark_example

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  benchmark_harness: ^1.0.0

dev_dependencies:
  mockito: ^4.1.1
  pedantic: ^1.8.0
  test: ^1.6.0


